import json
a = '-----BEGIN CERTIFICATE-----\nMIIDWTCCAkGgAwIBAgIUBbELns6cRV27KdkX+i02uUIagykwDQYJKoZIhvcNAQEL\nBQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g\nSW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTE5MDUxNTA0MTIz\nM1oXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0\nZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALCCSPOXaDPIARl1IlEZ\neZ0Dgyp2UAUDGCkBNHtZyCyDlWnFA4TtGkJ/+VR/FNbXGq81iu9SgFfhckeI8G6w\nqU4dBnjIPnWcRyB9+9LaUOKoAV8d5D1fV3tjpF/othVKdN17J8AChsJQhO9Urlxd\nRIvLoC8BwnBTnzoa7l/0VotglpShKBs1D2+PY/vQcF4yhd8XIM7Pmt3BFpNGXXZi\nNhpKjDLgVBqEL2/GUbEFYXcTG/i23VgZxhlk2Ftoh+Mowo1E64Iymb3hiFMPplnA\nVwJCWDahQlQpCIimKXavy0eZaOUwWZ6KXOUTfMEJdFTSaAt1YogxcPLqTyAt945a\nm9sCAwEAAaNgMF4wHwYDVR0jBBgwFoAUcZGPez6I+F8CgdnR2srd7MV+i/cwHQYD\nVR0OBBYEFO1BgceVjZuS1AGbpH4AIr58MUaIMAwGA1UdEwEB/wQCMAAwDgYDVR0P\nAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQCB85LOptQOrMAo1lqoeWbfR3o8\nPRKYrHfnIh67GpKBFZVokVJGnov0SB+kJ3GdxI/y72U3FCJgFXi5tCmesM71fjh7\nxfRFvt+lrjy4B9EviEeBKgv6LUiXS2O2C24ouxnirKImCOLy0vhne3c9r9x9AphD\nZIiAlVSWvtKklokqswkSZGrycqlb8yVBDOoks/pE98/ZnrBWP+sslHl3qrKGltsC\nY2ucwGx6f38f+Dq/I8FiRTosCDSgQ1U5KrRz3g/aTMv0O9n8N3u7d+GiJjyl8HQf\nuwm4zr/7yKmA+LLR/VKNpjFReRZDIjTOwPCyC/d5OsvLgxpY2dIq2/IpR/eB\n-----END CERTIFICATE-----\n'
# using replace

b = a.replace('-----BEGIN CERTIFICATE-----\n', '').replace('\n-----END CERTIFICATE-----\n','')

msg  = {}

msg['CSR'] = b

jmsg = json.dumps(msg)

print(type(jmsg), type(msg))
print(jmsg)
